### ISSUE TITLE
Handle multiple failing rules per line

### ISSUE THREAD

**Issue by AdarshKonchady** [akonchady/disable-eslint-issues-cli#1]
If a line has more than 1 eslint issues, add a comma-separated list of the rules rather than generating 1 `eslint-disable-next-line` for each failing rule.

**Comment by AndersDJohnson** [comment]
Wasn't this fixed in 6624ad370061bf8085c489800c8791ff06892e82?

**Comment by AdarshKonchady** [comment]
Yes this can be closed. Thanks !
